### ISSUE TITLE
Delimiters not working for "[ " and " ]"

### ISSUE THREAD

**Issue by Autoflow** [BorisMoore/jsviews#443] opened 2020-02-04 15:42 UTC
Hi, after a long search for practical delimiters i found "[ " and " ]" for myself being easy to read.
Now there's a problem with conditional sections. 

This [jsfiddle](https://jsfiddle.net/d6v52u90/1/) says: JsRender Error: Syntax error
Unmatched or missing {{/else}}, in template: [ if checked ] true [ else ] false [ /if ] 

Without whitespaces everything works fine so my question is if this issue can be fixed ?

**Comment by BorisMoore** [comment] 2020-02-04 23:23
Yes, that will not work. The delimiters must consist of two non-alphanumeric (and non-space) characters. I
I'll update the docs [here](https://www.jsviews.com/#settings/delimiters) to be more specific concerning white space characters.

You can do "[_" and "_]" for example....

**Comment by BorisMoore** [comment] 2020-02-12 00:03
I'll close this since the behavior is 'by design' - and we won't be able to allow using white-space within delimiters....

**Closed by BorisMoore** 2020-02-12 00:03 UTC
Labels: By design
