### ISSUE TITLE
Top-level data-link="{for...}" does not work on a 'select' element

### ISSUE THREAD

**Issue by alnico2001** [BorisMoore/jsviews#456] opened 2023-05-24 19:48 UTC
If you replace `<select>` with a `<div>`, it renders fine.

https://jsfiddle.net/alnico/ubLzcxy7

**Comment by alnico2001** [comment] 2023-05-30 13:35
Ah yes, I should have caught that...1st time doing top-level data linking.
Thanks Boris!

**Comment by BorisMoore** [comment] 2023-05-30 19:48
BTW, the same syntax for multiple targets, and the `html{}` target for `<select>` apply equally to regular linked template binding, as well as top-level binding.

see: https://jsfiddle.net/BorisMoore/vjz8f5h0/

Closing as "question" (not a bug)

**Closed by BorisMoore** 2023-05-30 19:48 UTC
Labels: Question, N/A
