### ISSUE TITLE
?: operator in css-height and css-width

### ISSUE THREAD

**Issue by Mytia** [BorisMoore/jsviews#331] opened 2016-01-12 17:06 UTC
Little bug here

http://jsfiddle.net/y43cs47y/9/

Error in console.
It works if wrap ~height?~height:100 with brackets. The same thing with css-width, maybe with something else...

**Comment by BorisMoore** [comment] 2016-01-13 23:03
Yes, the issue there is that your syntax conflicts with the syntax for two-way binding with a convertBack converter:

    <input data-link="{cvt:name:cvtBack}" >

I have a parser fix prepared for the next update, but for now you can use any of the following forms to make the ternary statement work without conflict in the current version of the parser: 

    {:~height ? ~height : 100}
    {:~height?~height: 100}
    {:~height?~height:100 }
    {:(~height?~height:100)}

All of the above make it clear that this is not two-way binding. 

BTW the issue is not specific to css-height or css-width at all...

**Comment by Mytia** [comment] 2016-01-14 12:30
Yes, thanks, the same thing with tag args and params

http://jsfiddle.net/y43cs47y/13/

**Comment by BorisMoore** [comment] 2016-01-14 16:26
Correct - they are also fixed in the change I have for the next update...

**Comment by BorisMoore** [comment] 2016-01-28 03:59
This has been fixed with update v0.9.72.

See http://jsfiddle.net/y43cs47y/9/ and http://jsfiddle.net/y43cs47y/14/

**Closed by BorisMoore** 2016-01-28 03:59 UTC
