### ISSUE TITLE
props change not refresh dom when {^{prop}} {^{if}}

### ISSUE THREAD

**Issue by sany98215** [BorisMoore/jsviews#428] opened 2019-06-10 03:49 UTC
```
<!DOCTYPE html>
<!-- To run the current sample code in your own environment, copy this to an html page. -->

<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://www.jsviews.com/download/jsviews.min.js"></script>
  <link href="https://www.jsviews.com/samples/samples.css" rel="stylesheet" />
</head>
<body>

<div id="team"></div>

<script id="teamTemplate" type="text/x-jsrender">
  <button data-link="{on addMember}">Add</button>
  <button data-link="{on replaceMembers}">Replace</button>
  <button data-link="{on changeMembers}">Change</button>
  <ol>
    {^{props members}}
      <li>
        {^{if prop.startsWith("Peter")}}
        <select data-link="prop"/>
        {{else}}
        <input data-link="prop"/>
        {{/if}}
        {^{>prop}}
        <span class="remove" data-link="{on ~root.removeMember key}"></span>
      </li>
    {{else}}
      There are no members
    {{/props}}
  </ol>
</script>


<script>
var team = {
  members: {m1: "Robert", m2: "Sarah"},
  addMember: function() {
    $.observable(this.members).setProperty("n" + cnt, "new" + cnt++);
  }, 
  removeMember: function(key) {
    $.observable(this.members).removeProperty(key);
  },
  replaceMembers: function() {
    $.observable(this).setProperty("members", {m1: "Peter", m2: "Octavia", m3: "Xavier"});
  },
  changeMembers: function() {
    for (var property in this.members) {
      if (property !== $.expando) {
        $.observable(this.members).setProperty(property, this.members[property] + cnt++);
      }
    }
  }
},
cnt = 1;

$.templates("#teamTemplate").link("#team", team);
</script>

</body>
</html>
```

**Comment by sany98215** [comment] 2019-06-10 04:06
version 1.0.2 . when prop change to Perter***, input element do not change to select

**Comment by BorisMoore** [comment] 2019-06-12 07:02
Thanks for this.  I'm travelling for the rest of June, so may not be able to look closer at this until I return...

**Comment by johan-ohrn** [comment] 2019-06-22 13:01
I created this [fiddle](http://jsfiddle.net/sbqt3041/) to give a shorter demonstration of the problem. 
Type into the textbox with the console open. You'll see that 'b' is logged each time you type something but 'a' is only logged on initial rendering. I believe that jsviews might incorrectly be treating the ```.startsWith...``` expression as a property path and is monitoring it for changes instead of the test property.

**Comment by BorisMoore** [comment] 2019-07-06 22:47
Yes, for it to work as intended you have to write `test^startsWith(...)`. I think that it actually makes sense to require that syntax if you want to 'observe' changes to `test`. For any property path `a.b.c.d` or `a().b().c().d()` or some mixture `a.b().c.d()` it should make no difference whether they are objects or strings and whether the 'members' are instance properties or prototype members. And those with parens may be simple functions, or computed properties, with depends etc.

Either way you are listening to leaf changes only, unless you use the `^` separator.

I appreciate that people may expect test.startsWith() to 'listen' to changes in the `test` string, but to introduce special behavior no longer based on the syntactical rules, but instead based on detecting that `test` is a string and `startsWith()` is in the String prototype, could be difficult to implement, buggy, and unpredictable in behavior....

That's my initial take. What do you think? 

BTW another simple test case would be:

```
<input data-link="test" />
{^{:test^indexOf('a') }}
```

**Comment by sany98215** [comment] 2019-07-12 03:29
Thanks for your reply.I understand what is it.

**Comment by BorisMoore** [comment] 2019-07-26 21:33
OK - I'll close this.

**Closed by BorisMoore** 2019-07-26 21:33 UTC
Labels: Question
