### ISSUE TITLE
updateValue not working correctly for 2-way bound tag properties with a path expression containing index [] operator

### ISSUE THREAD

**Issue by johan-ohrn** [BorisMoore/jsviews#414] opened 2019-02-06 11:52 UTC
I was trying to replicate an issue we're having when I stumbled upon something odd. Have a look at this [fiddle](https://jsfiddle.net/hn5wp20v/1/) with the browser console open.

I'm trying to 2-way bind properties such as this:
```{^{mytag p1=arr[0].data /}}```

Whenever I use the index operator in the path expression, be it to access an item in an array or a property on an object, updateValue() fails to write back the value to the data context.

As demonstrated in the fiddle the actual value flows correctly from the data context into the tag instance but not from the tag instance back to the data context.

**Comment by BorisMoore** [comment] 2019-02-07 06:37
Excellent, that is a good catch.

You are right, it is a bug. I think I have a fix. I'll get it to you soon. 

Meantime if you write  `{^{mytag ^p1=arr[0].data /}}` it should bind correctly...

**Comment by BorisMoore** [comment] 2019-02-09 04:45
The attached file is my probable next update, and includes a fix for this issue. Let me know if it works correctly for you...

[jsviews.js.txt](https://github.com/BorisMoore/jsviews/files/2847510/jsviews.js.txt)

**Comment by johan-ohrn** [comment] 2019-02-11 13:48
Do you by any chance happen to have the file split up into jsrender, jsviews and jsobservable? I tried to split it up myself but I'm facing some issues with it.

**Comment by BorisMoore** [comment] 2019-02-11 16:08
Sure: [download.zip](https://github.com/BorisMoore/jsviews/files/2851879/download.zip)

Let me know if this doesn't work for you.

**Comment by BorisMoore** [comment] 2019-02-11 19:28
I have updated jsviews.com with this v1.0.2 update. https://www.jsviews.com/#download. I think the fix is good, but let me know how it works for you... Thanks again for calling this out!

**Comment by BorisMoore** [comment] 2019-02-11 22:06
Fixed in v1.0.2

**Comment by johan-ohrn** [comment] 2019-02-12 10:50
I can now confirm that version 1.0.2 work correctly in our application.
Thanks alot!

**Comment by johan-ohrn** [comment] 2020-06-24 10:05
I found some issues which I think are closely related to this issue. Please have a look at this [fiddle](https://jsfiddle.net/Lnk43c52/4/)

The following two expressions don't work correctly:
```
{^{mytag
    p5=obj5.x['data']
    p6=obj6['x']['data']
}}
```

**Comment by BorisMoore** [comment] 2020-06-26 05:59
Hi Johan. I think that what you are seeing is a limitation on the current implementation that is more general - and does not only concern `.updateValue()`.

In fact for JsRender (as well as for initial rendering of data-link expressions in JsViews) there is support for [chained paths](https://www.jsviews.com/#paths@bracketnotation) that can use either the `.` accessor or the `[]` accessor.

But the data-binding will only listen to observable changes to properties with the `.` syntax.

For example `{^{:data.person.address.place.type}}` will listen to changes to the `type` property of `place`, and `{^{:data^person.address.place.type}}` will also listen to changes in the `person` property of `data`, the `address` property of `person` or the `place` property of `address`.
 
But `{^{:data^person['address'].place['type']}}` will only listen to changes in the `person` property of `data`, or the `place` property of `address`. And `{^{:data.person['address'].place['type']}}` will render correctly, but will not respond to any observable changes.

Similarly two-way binding will work for this: `<input data-link="data.person['address'].place.type" />` and trigger changes to the type property. But two-way binding will not work for this: `<input data-link="data.person['address'].place['type']" />` 

Now one could presumable add support for data-linking on `[]` accessor paths, such as

`<input data-link="person['name']" />`

But is there a reason why one can't simply use the `.` accessor instead: `<input data-link="person.name" />`? Do you have a scenario that needs that `[]` support? I know it would allow you to bind to property names such as "first.name" etc as in [the JsRender example](https://www.jsviews.com/#paths@bracketnotation) - but that seems to me to be a somewhat fringe scenario.

And if we did add the above support, what about this, for example

`<input data-link="person[~firstOrLast]" />`

where the helper can take the value "firstName" or "lastName". In that case do we provide two-way binding to the property name `person.firstName` if ~firstOrLast initially has that value. Then do we track changes in `firstOrLast` and add two-way binding to `last` if `firstOrLast` switches to that. 

Given the different potential ramifications, I think we should stay with current support. Maybe we need to add error messages or documentation about this limitation, but I'm not convinced that it is necessary to do so...

What do you think? Does all this make sense?

**Comment by BorisMoore** [comment] 2020-07-09 22:09
Hi Johan, resolving this as by design, for your additional cases added in the [comment above](https://github.com/BorisMoore/jsviews/issues/414#issuecomment-648726646)

**Closed by BorisMoore** 2020-07-09 22:09 UTC
Labels: Bug, By design, Resolved

**Comment by johan-ohrn** [comment] 2020-07-14 06:11
Your explanation is very thorough and I can see how it would become extremely complicated if the expression inside the [] are not constant such as ```person[~firstName]```.
My initial use case was to link to (and write back from a tag) it's state into the viewModel. Something like this:
```
{{for arrayOfSomething ~vm=#data}}
  {^{myTag linkedProp=~vm.myState[#getIndex()] }}
 ...
  {{/myTag}}
{{/for}}
```

I didn't want to clutter the items in ```arrayOfSomething``` with the state of myTag. I worked around the problem by creating a state object for each item in arrayOfSomething and changed the myTag template expression into ```  {^{myTag linkedProp=~vm.myState[#getIndex()].value }}```

So I'm all good. Thanks!
